CREATE TABLE Calendar (
    id binary(16) PRIMARY KEY,
    start DATETIME NOT NULL,
    end DATETIME NOT NULL,
    subject VARCHAR(255),
    description VARCHAR(1023),
    added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
